import { FeatureCategory } from '../types/Features';
import {
  FiUser,
  FiLock,
  FiSmartphone,
  FiNavigation,
  FiImage,
  FiDatabase,
  FiMapPin,
  FiWifi,
  FiGrid,
  FiLayers,
  FiCode,
  FiTool,
  FiShield,
  FiCopy,
  FiBell,
  FiCamera,
  FiUpload,
  FiDownload,
  FiShare2,
  FiActivity,
  FiBluetooth,
  FiCreditCard,
} from 'react-icons/fi';

export const featureCategories: FeatureCategory[] = [
  {
    id: 'auth',
    name: 'Authentication & Permissions',
    description: 'User authentication, SSO, and permission handling',
    icon: FiLock,
    color: 'blue',
    items: [
      {
        id: 'auth-sso',
        title: 'SSO Authentication',
        description: 'Get auth code and implement SSO flow with Viettel platform',
        icon: FiUser,
        path: '/auth/sso',
        status: 'stable',
        tags: ['wv.getAuthCode', 'authentication'],
      },
      {
        id: 'auth-permissions',
        title: 'Device Permissions',
        description: 'Request and manage device permissions (camera, location, etc)',
        icon: FiShield,
        path: '/auth/permissions',
        status: 'stable',
        tags: ['wv.getSetting', 'wv.authorize'],
      },
    ],
  },
  {
    id: 'device',
    name: 'Device & System',
    description: 'Device information, clipboard, and system features',
    icon: FiSmartphone,
    color: 'green',
    items: [
      {
        id: 'device-info',
        title: 'Device Information',
        description: 'Get device details, OS version, and platform info',
        icon: FiSmartphone,
        path: '/device/info',
        status: 'stable',
        tags: ['device-info', 'system'],
      },
      {
        id: 'device-clipboard',
        title: 'Clipboard Operations',
        description: 'Copy text to clipboard with native integration',
        icon: FiCopy,
        path: '/device/clipboard',
        status: 'stable',
        tags: ['WVBase.copyToClipboard'],
      },
      {
        id: 'device-lifecycle',
        title: 'App Lifecycle',
        description: 'Handle background/foreground events and app state',
        icon: FiActivity,
        path: '/device/lifecycle',
        status: 'stable',
        tags: ['WV.Event.APP.Background', 'WV.Event.APP.Active'],
      },
    ],
  },
  {
    id: 'navigation',
    name: 'Navigation & UI',
    description: 'Screen navigation, modals, and UI components',
    icon: FiNavigation,
    color: 'purple',
    items: [
      {
        id: 'nav-routing',
        title: 'Route Navigation',
        description: 'Navigate between screens with parameters and deep linking',
        icon: FiNavigation,
        path: '/navigation/routing',
        status: 'stable',
        tags: ['routing', 'navigation'],
      },
      {
        id: 'nav-modals',
        title: 'Modals & Dialogs',
        description: 'Show alerts, confirmations, and custom modals',
        icon: FiGrid,
        path: '/navigation/modals',
        status: 'stable',
        tags: ['modal', 'dialog', 'alert'],
      },
      {
        id: 'nav-notifications',
        title: 'Toast Notifications',
        description: 'Display toast messages and notifications',
        icon: FiBell,
        path: '/navigation/toast',
        status: 'stable',
        tags: ['WVBase.notify', 'toast'],
      },
    ],
  },
  {
    id: 'media',
    name: 'Media & Files',
    description: 'Camera, image picker, and file operations',
    icon: FiImage,
    color: 'pink',
    items: [
      {
        id: 'media-camera',
        title: 'Camera Access',
        description: 'Take photos using device camera with native integration',
        icon: FiCamera,
        path: '/media/camera',
        status: 'stable',
        tags: ['camera', 'photo'],
      },
      {
        id: 'media-picker',
        title: 'Image Picker',
        description: 'Select images from gallery with preview',
        icon: FiImage,
        path: '/media/picker',
        status: 'stable',
        tags: ['gallery', 'image-picker'],
      },
      {
        id: 'media-upload',
        title: 'File Upload',
        description: 'Upload files with progress tracking',
        icon: FiUpload,
        path: '/media/upload',
        status: 'stable',
        tags: ['upload', 'file'],
      },
    ],
  },
  {
    id: 'storage',
    name: 'Storage & Cache',
    description: 'Local storage, secure storage, and caching',
    icon: FiDatabase,
    color: 'yellow',
    items: [
      {
        id: 'storage-local',
        title: 'Local Storage',
        description: 'Store and retrieve data locally with persistence',
        icon: FiDatabase,
        path: '/storage/local',
        status: 'stable',
        tags: ['localStorage', 'persistence'],
      },
      {
        id: 'storage-secure',
        title: 'Secure Storage',
        description: 'Encrypted storage for sensitive data',
        icon: FiLock,
        path: '/storage/secure',
        status: 'stable',
        tags: ['encryption', 'security'],
      },
    ],
  },
  {
    id: 'location',
    name: 'Location Services',
    description: 'GPS, geolocation, and maps integration',
    icon: FiMapPin,
    color: 'red',
    items: [
      {
        id: 'location-current',
        title: 'Get Location',
        description: 'Get current GPS coordinates and location data',
        icon: FiMapPin,
        path: '/location/current',
        status: 'stable',
        tags: ['GPS', 'geolocation'],
      },
      {
        id: 'location-tracking',
        title: 'Location Tracking',
        description: 'Track user location in real-time',
        icon: FiNavigation,
        path: '/location/tracking',
        status: 'beta',
        tags: ['tracking', 'GPS'],
      },
    ],
  },
  {
    id: 'network',
    name: 'Network & API',
    description: 'HTTP requests, WebSocket, and API integration',
    icon: FiWifi,
    color: 'indigo',
    items: [
      {
        id: 'network-http',
        title: 'HTTP Requests',
        description: 'Make API calls with Axios and error handling',
        icon: FiWifi,
        path: '/network/http',
        status: 'stable',
        tags: ['axios', 'api', 'fetch'],
      },
      {
        id: 'network-websocket',
        title: 'WebSocket',
        description: 'Real-time communication with WebSocket',
        icon: FiActivity,
        path: '/network/websocket',
        status: 'stable',
        tags: ['websocket', 'realtime'],
      },
    ],
  },
  {
    id: 'native',
    name: 'Native Features',
    description: 'QR scanner, Bluetooth, and native capabilities',
    icon: FiLayers,
    color: 'teal',
    items: [
      {
        id: 'native-qr',
        title: 'QR/Barcode Scanner',
        description: 'Scan QR codes and barcodes using device camera',
        icon: FiCamera,
        path: '/native/qr-scanner',
        status: 'stable',
        tags: ['qr', 'barcode', 'scanner'],
      },
      {
        id: 'native-bluetooth',
        title: 'Bluetooth',
        description: 'Connect and communicate with Bluetooth devices',
        icon: FiBluetooth,
        path: '/native/bluetooth',
        status: 'beta',
        tags: ['bluetooth', 'BLE'],
      },
      {
        id: 'native-payment',
        title: 'Payment Integration',
        description: 'Process payments through native payment gateway',
        icon: FiCreditCard,
        path: '/native/payment',
        status: 'experimental',
        tags: ['payment', 'transaction'],
      },
      {
        id: 'native-share',
        title: 'Share Content',
        description: 'Share text, images, and links to other apps',
        icon: FiShare2,
        path: '/native/share',
        status: 'stable',
        tags: ['share', 'social'],
      },
    ],
  },
  {
    id: 'state',
    name: 'State Management',
    description: 'Zustand, Context, and state patterns',
    icon: FiCode,
    color: 'orange',
    items: [
      {
        id: 'state-zustand',
        title: 'Zustand Store',
        description: 'Global state management with Zustand',
        icon: FiDatabase,
        path: '/state/zustand',
        status: 'stable',
        tags: ['zustand', 'state', 'store'],
      },
      {
        id: 'state-context',
        title: 'React Context',
        description: 'Context API patterns and usage',
        icon: FiLayers,
        path: '/state/context',
        status: 'stable',
        tags: ['context', 'react'],
      },
    ],
  },
  {
    id: 'ui',
    name: 'UI Components',
    description: 'Tailwind components, forms, and design patterns',
    icon: FiTool,
    color: 'cyan',
    items: [
      {
        id: 'ui-forms',
        title: 'Forms & Validation',
        description: 'Form handling with validation patterns',
        icon: FiCode,
        path: '/ui/forms',
        status: 'stable',
        tags: ['forms', 'validation'],
      },
      {
        id: 'ui-buttons',
        title: 'Button Variants',
        description: 'Different button styles and states',
        icon: FiGrid,
        path: '/ui/buttons',
        status: 'stable',
        tags: ['tailwind', 'buttons'],
      },
      {
        id: 'ui-layout',
        title: 'Layout Patterns',
        description: 'Responsive layouts and grid systems',
        icon: FiGrid,
        path: '/ui/layout',
        status: 'stable',
        tags: ['tailwind', 'responsive'],
      },
    ],
  },
];