import { FeatureCategory } from '../types/Features';
import {
  FiUser,
  FiLock,
  FiSmartphone,
  FiNavigation,
  FiImage,
  FiDatabase,
  FiMapPin,
  FiWifi,
  FiGrid,
  FiCopy,
  FiBell,
  FiCamera,
  FiUpload,
  FiFile,
  FiActivity,
  FiBluetooth,
  FiPhone,
  FiUsers,
  FiZap,
  FiVolume2,
  FiMonitor,
  FiRotateCw,
} from 'react-icons/fi';

export const featureCategories: FeatureCategory[] = [
  {
    id: 'permissions',
    name: 'Device Permissions',
    description: 'Request and manage device permissions',
    icon: FiLock,
    color: 'blue',
    items: [
      {
        id: 'device-permissions',
        title: 'Device Permissions',
        description: 'Get and request device permissions (camera, location, etc)',
        icon: FiLock,
        path: '/permissions/device',
        status: 'stable',
        tags: ['wv.getSetting', 'wv.authorize'],
      },
    ],
  },
  {
    id: 'auth',
    name: 'User Data Permission',
    description: 'SSO authentication and user authorization',
    icon: FiUser,
    color: 'purple',
    items: [
      {
        id: 'auth-sso',
        title: 'SSO Authentication',
        description: 'Get auth code for SSO flow',
        icon: FiUser,
        path: '/authentication/sso',
        status: 'stable',
        tags: ['wv.getAuthCode'],
      },
    ],
  },
  {
    id: 'base',
    name: 'Base APIs',
    description: 'Core utilities and base functionality',
    icon: FiGrid,
    color: 'green',
    items: [
      {
        id: 'base-clipboard',
        title: 'Clipboard',
        description: 'Copy text to clipboard',
        icon: FiCopy,
        path: '/base/clipboard',
        status: 'stable',
        tags: ['WVBase.copyToClipboard'],
      },
      {
        id: 'base-install-check',
        title: 'App Install Check',
        description: 'Check if apps are installed',
        icon: FiSmartphone,
        path: '/base/install',
        status: 'stable',
        tags: ['WVBase.isInstall', 'WVBase.isAppsInstalled'],
      },
      {
        id: 'base-notify',
        title: 'Notifications',
        description: 'Show toast notifications',
        icon: FiBell,
        path: '/base/notify',
        status: 'stable',
        tags: ['WVBase.notify'],
      },
      {
        id: 'base-browser',
        title: 'Open Browser',
        description: 'Open URLs in external browser',
        icon: FiNavigation,
        path: '/base/browser',
        status: 'stable',
        tags: ['WVBase.openBrowser'],
      },
      {
        id: 'base-background',
        title: 'Background Color',
        description: 'Set app background color',
        icon: FiMonitor,
        path: '/base/background',
        status: 'stable',
        tags: ['WVBase.setBackgroundColor'],
      },
      {
        id: 'base-can-use',
        title: 'API Availability',
        description: 'Check if API is available',
        icon: FiZap,
        path: '/base/can-use',
        status: 'stable',
        tags: ['WVBase.canIUse'],
      },
      {
        id: 'base-close',
        title: 'Close MiniApp',
        description: 'Close the current MiniApp',
        icon: FiNavigation,
        path: '/base/close',
        status: 'stable',
        tags: ['WVMiniApp.close'],
      },
    ],
  },
  {
    id: 'navigation',
    name: 'Navigation',
    description: 'Page navigation and routing',
    icon: FiNavigation,
    color: 'indigo',
    items: [
      {
        id: 'nav-pop',
        title: 'Navigate Back',
        description: 'Pop current page from navigation stack',
        icon: FiNavigation,
        path: '/navigation/pop',
        status: 'stable',
        tags: ['WVNavigator.pop'],
      },
      {
        id: 'nav-push',
        title: 'Navigate Forward',
        description: 'Push new page to navigation stack',
        icon: FiNavigation,
        path: '/navigation/push',
        status: 'stable',
        tags: ['WVNavigator.push'],
      },
      {
        id: 'nav-miniapp',
        title: 'Navigate to MiniApp',
        description: 'Navigate to another MiniApp',
        icon: FiNavigation,
        path: '/navigation/miniapp',
        status: 'stable',
        tags: ['wv.navigateToMiniapp'],
      },
    ],
  },
  {
    id: 'interaction',
    name: 'Interaction',
    description: 'UI interactions, dialogs, and alerts',
    icon: FiGrid,
    color: 'pink',
    items: [
      {
        id: 'ui-loading',
        title: 'Loading Box',
        description: 'Show and hide loading indicators',
        icon: FiRotateCw,
        path: '/interaction/loading',
        status: 'stable',
        tags: ['WVUI.showLoadingBox', 'WVUI.hideLoadingBox'],
      },
      {
        id: 'ui-keyboard',
        title: 'Keyboard Control',
        description: 'Hide keyboard',
        icon: FiGrid,
        path: '/interaction/keyboard',
        status: 'stable',
        tags: ['WVUI.hideKeyboard'],
      },
      {
        id: 'ui-toast',
        title: 'Toast Messages',
        description: 'Show toast notifications',
        icon: FiBell,
        path: '/interaction/toast',
        status: 'stable',
        tags: ['WVUIToast.toast'],
      },
      {
        id: 'ui-dialog',
        title: 'Dialogs',
        description: 'Alert, confirm, and prompt dialogs',
        icon: FiGrid,
        path: '/interaction/dialog',
        status: 'stable',
        tags: ['WVUIDialog.alert', 'WVUIDialog.confirm', 'WVUIDialog.prompt'],
      },
      {
        id: 'ui-action-sheet',
        title: 'Action Sheet',
        description: 'Show action sheet with options',
        icon: FiGrid,
        path: '/interaction/action-sheet',
        status: 'stable',
        tags: ['WVUIActionSheet.show'],
      },
      {
        id: 'ui-navbar',
        title: 'Navigation Bar',
        description: 'Update and get navigation bar info',
        icon: FiNavigation,
        path: '/interaction/navbar',
        status: 'stable',
        tags: ['WVNavigationBar.update', 'WVNavigationBar.getHeight'],
      },
    ],
  },
  {
    id: 'multimedia',
    name: 'Multimedia',
    description: 'Images, video, audio, and camera',
    icon: FiImage,
    color: 'orange',
    items: [
      {
        id: 'media-image',
        title: 'Image Operations',
        description: 'Save images to photo album',
        icon: FiImage,
        path: '/multimedia/image',
        status: 'stable',
        tags: ['WVImage.saveImage'],
      },
      {
        id: 'media-video',
        title: 'Video Operations',
        description: 'Choose and save videos',
        icon: FiImage,
        path: '/multimedia/video',
        status: 'stable',
        tags: ['WVVideo.chooseVideo', 'WVVideo.saveVideoToPhotosAlbum'],
      },
      {
        id: 'media-audio',
        title: 'Audio',
        description: 'Play system sounds',
        icon: FiVolume2,
        path: '/multimedia/audio',
        status: 'stable',
        tags: ['WVAudio.playSystemSound'],
      },
      {
        id: 'media-camera',
        title: 'Camera',
        description: 'Take photos with device camera',
        icon: FiCamera,
        path: '/multimedia/camera',
        status: 'stable',
        tags: ['WVCamera.takePhoto'],
      },
      {
        id: 'media-storage',
        title: 'Storage',
        description: 'Local data storage operations',
        icon: FiDatabase,
        path: '/multimedia/storage',
        status: 'stable',
        tags: ['WVStorage.setItem', 'WVStorage.getItem', 'WVStorage.removeItem'],
      },
    ],
  },
  {
    id: 'file',
    name: 'File',
    description: 'File operations and management',
    icon: FiFile,
    color: 'yellow',
    items: [
      {
        id: 'file-read-write',
        title: 'File Read/Write',
        description: 'Read and write files',
        icon: FiFile,
        path: '/file/read-write',
        status: 'stable',
        tags: ['WVFile.write', 'WVFile.read'],
      },
      {
        id: 'file-info',
        title: 'File Info',
        description: 'Get file information',
        icon: FiFile,
        path: '/file/info',
        status: 'stable',
        tags: ['WVFile.getFileInfo'],
      },
      {
        id: 'file-download-upload',
        title: 'Download/Upload',
        description: 'Download and upload files',
        icon: FiUpload,
        path: '/file/transfer',
        status: 'stable',
        tags: ['WVFile.downloadFile', 'WVFile.uploadFile'],
      },
      {
        id: 'file-choose',
        title: 'Choose Files',
        description: 'Choose files from device',
        icon: FiFile,
        path: '/file/choose',
        status: 'stable',
        tags: ['WVFile.chooseFiles'],
      },
    ],
  },
  {
    id: 'location',
    name: 'Geographical Location',
    description: 'GPS and location services',
    icon: FiMapPin,
    color: 'red',
    items: [
      {
        id: 'location-get',
        title: 'Get Location',
        description: 'Get current GPS coordinates',
        icon: FiMapPin,
        path: '/location/get',
        status: 'stable',
        tags: ['WVLocation.getLocation'],
      },
      {
        id: 'location-search',
        title: 'Search Location',
        description: 'Search for locations',
        icon: FiMapPin,
        path: '/location/search',
        status: 'stable',
        tags: ['WVLocation.searchLocation'],
      },
    ],
  },
  {
    id: 'cookie',
    name: 'Cookie',
    description: 'Cookie read and write operations',
    icon: FiDatabase,
    color: 'teal',
    items: [
      {
        id: 'cookie-ops',
        title: 'Cookie Operations',
        description: 'Read and write cookies',
        icon: FiDatabase,
        path: '/cookie/operations',
        status: 'stable',
        tags: ['WVCookie.read', 'WVCookie.write'],
      },
    ],
  },
  {
    id: 'device',
    name: 'Device',
    description: 'Device information and capabilities',
    icon: FiSmartphone,
    color: 'cyan',
    items: [
      {
        id: 'device-system-info',
        title: 'System Information',
        description: 'Get device and OS information',
        icon: FiSmartphone,
        path: '/device/system-info',
        status: 'stable',
        tags: ['WVSystem.getSystemInfo', 'WVSystem.getSystemInfoSync'],
      },
      {
        id: 'device-detector',
        title: 'Device Detector',
        description: 'Detect device capabilities and properties',
        icon: FiSmartphone,
        path: '/device/detector',
        status: 'stable',
        tags: ['WVNativeDetector.isSimulator', 'WVNativeDetector.getDeviceYear'],
      },
    ],
  },
  {
    id: 'network',
    name: 'Network',
    description: 'Network status and connectivity',
    icon: FiWifi,
    color: 'blue',
    items: [
      {
        id: 'network-type',
        title: 'Network Type',
        description: 'Get current network type',
        icon: FiWifi,
        path: '/network/type',
        status: 'stable',
        tags: ['WVNetwork.getNetworkType'],
      },
    ],
  },
  {
    id: 'screen',
    name: 'Screen',
    description: 'Screen orientation and brightness',
    icon: FiMonitor,
    color: 'purple',
    items: [
      {
        id: 'screen-orientation',
        title: 'Screen Orientation',
        description: 'Get and set screen orientation',
        icon: FiRotateCw,
        path: '/screen/orientation',
        status: 'stable',
        tags: ['WVScreen.getOrientation', 'WVScreen.setOrientation'],
      },
      {
        id: 'screen-brightness',
        title: 'Screen Brightness',
        description: 'Get and set screen brightness',
        icon: FiMonitor,
        path: '/screen/brightness',
        status: 'stable',
        tags: ['WVScreen.setScreenBrightness', 'WVScreen.getScreenBrightness'],
      },
      {
        id: 'screen-capture',
        title: 'Screen Capture',
        description: 'Capture screenshot',
        icon: FiCamera,
        path: '/screen/capture',
        status: 'stable',
        tags: ['WVScreenCapture.capture'],
      },
    ],
  },
  {
    id: 'motion',
    name: 'Motion Detection',
    description: 'Accelerometer, gyroscope, and motion events',
    icon: FiActivity,
    color: 'green',
    items: [
      {
        id: 'motion-gestures',
        title: 'Motion Gestures',
        description: 'Detect blow, shake, and other gestures',
        icon: FiActivity,
        path: '/motion/gestures',
        status: 'stable',
        tags: ['WVMotion.listenBlow', 'WVMotion.listeningShake'],
      },
      {
        id: 'motion-sensors',
        title: 'Motion Sensors',
        description: 'Accelerometer, gyroscope, and compass',
        icon: FiActivity,
        path: '/motion/sensors',
        status: 'stable',
        tags: ['WVMotion.startAccelerometer', 'WVMotion.listenGyro', 'WVMotion.startCompass'],
      },
      {
        id: 'motion-vibrate',
        title: 'Vibration',
        description: 'Trigger device vibration',
        icon: FiActivity,
        path: '/motion/vibrate',
        status: 'stable',
        tags: ['WVMotion.vibrate'],
      },
    ],
  },
  {
    id: 'sound',
    name: 'Sound',
    description: 'Sound notifications and alerts',
    icon: FiVolume2,
    color: 'orange',
    items: [
      {
        id: 'sound-beep',
        title: 'Beep Notification',
        description: 'Play beep sound',
        icon: FiVolume2,
        path: '/sound/beep',
        status: 'stable',
        tags: ['WVNotification.beep'],
      },
    ],
  },
  {
    id: 'call',
    name: 'Call',
    description: 'Phone call functionality',
    icon: FiPhone,
    color: 'pink',
    items: [
      {
        id: 'call-dial',
        title: 'Dial Phone',
        description: 'Dial phone number',
        icon: FiPhone,
        path: '/call/dial',
        status: 'stable',
        tags: ['WVCall.dial', 'WVCall.call'],
      },
    ],
  },
  {
    id: 'app-info',
    name: 'App Information',
    description: 'Application state and settings',
    icon: FiSmartphone,
    color: 'indigo',
    items: [
      {
        id: 'app-state',
        title: 'App State',
        description: 'Get application state and settings',
        icon: FiSmartphone,
        path: '/app/state',
        status: 'stable',
        tags: ['WVApplication.appState', 'WVApplication.getNotificationSettings'],
      },
      {
        id: 'app-settings',
        title: 'Open Settings',
        description: 'Open app settings',
        icon: FiSmartphone,
        path: '/app/settings',
        status: 'stable',
        tags: ['WVApplication.openSettings'],
      },
    ],
  },
  {
    id: 'contacts',
    name: 'Address Book',
    description: 'Access and manage contacts',
    icon: FiUsers,
    color: 'teal',
    items: [
      {
        id: 'contacts-auth',
        title: 'Contacts Authorization',
        description: 'Request contacts permission',
        icon: FiLock,
        path: '/contacts/auth',
        status: 'stable',
        tags: ['WVContacts.askAuth', 'WVContacts.authStatus'],
      },
      {
        id: 'contacts-operations',
        title: 'Contacts Operations',
        description: 'Choose, find, and add contacts',
        icon: FiUsers,
        path: '/contacts/operations',
        status: 'stable',
        tags: ['WVContacts.choose', 'WVContacts.find', 'WVContacts.addPhoneContact'],
      },
    ],
  },
  {
    id: 'scan',
    name: 'Scan',
    description: 'QR code and barcode scanning',
    icon: FiCamera,
    color: 'cyan',
    items: [
      {
        id: 'scan-qr',
        title: 'QR/Barcode Scanner',
        description: 'Scan QR codes and barcodes',
        icon: FiCamera,
        path: '/scan/qr',
        status: 'stable',
        tags: ['WVScan.scan'],
      },
    ],
  },
  {
    id: 'battery',
    name: 'Battery',
    description: 'Battery information',
    icon: FiZap,
    color: 'yellow',
    items: [
      {
        id: 'battery-info',
        title: 'Battery Information',
        description: 'Get battery level and status',
        icon: FiZap,
        path: '/battery/info',
        status: 'stable',
        tags: ['WVBattery.getBatteryInfo', 'WVBattery.getBatteryInfoSync'],
      },
    ],
  },
  {
    id: 'bluetooth',
    name: 'Bluetooth',
    description: 'Bluetooth Low Energy (BLE) operations',
    icon: FiBluetooth,
    color: 'blue',
    items: [
      {
        id: 'bluetooth-scan',
        title: 'Bluetooth Scan',
        description: 'Scan for BLE devices',
        icon: FiBluetooth,
        path: '/bluetooth/scan',
        status: 'stable',
        tags: ['WVBluetooth.requestAuthorization', 'WVBluetooth.scan'],
      },
      {
        id: 'bluetooth-connect',
        title: 'Bluetooth Connection',
        description: 'Connect to BLE devices',
        icon: FiBluetooth,
        path: '/bluetooth/connect',
        status: 'stable',
        tags: ['WVBluetooth.connect', 'WVBluetooth.disconnect'],
      },
      {
        id: 'bluetooth-operations',
        title: 'Bluetooth Operations',
        description: 'Read, write, and notify BLE characteristics',
        icon: FiBluetooth,
        path: '/bluetooth/operations',
        status: 'stable',
        tags: ['WVBluetooth.readValue', 'WVBluetooth.writeValue'],
      },
    ],
  },
  {
    id: 'events',
    name: 'Other Features',
    description: 'App lifecycle and special events',
    icon: FiActivity,
    color: 'purple',
    items: [
      {
        id: 'events-lifecycle',
        title: 'App Lifecycle',
        description: 'Handle background/foreground events',
        icon: FiActivity,
        path: '/events/lifecycle',
        status: 'stable',
        tags: ['WV.Event.APP.Background', 'WV.Event.APP.Active', 'WindVaneReady'],
      },
      {
        id: 'events-scroll',
        title: 'Scroll Events',
        description: 'Pull refresh and infinite scroll',
        icon: FiRotateCw,
        path: '/events/scroll',
        status: 'stable',
        tags: ['Pull Refresh', 'Infinite Scroll'],
      },
    ],
  },
];